spring.application.name=jangsu
spring.datasource.url=jdbc:mysql://10.20.151.86:3306/test
spring.datasource.username=rocky1
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.cache=false
